version: '3.7'
services:
  #################################################################
  # mySQL                                                    #
  #################################################################
  mysqld:
    image: mysql:latest
    container_name: mysqld
    ports:
      - 33060:33060
      - 3306:3306
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: photo_app
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_HOST: 0.0.0.0
    networks:
      - commonNetwork

  #################################################################
  # trading101                                                     #
  #################################################################
  trading101:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARTIFACT_PATH=mobile-app-1.0.0.jar
    container_name: trading101
    depends_on:
      - mysqld
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=debug"
      - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysqld:3306/photo_app"
      - "SPRING_DATASOURCE_USERNAME=bob"
      - "SPRING_DATASOURCE_PASSWORD=bob"
    networks:
      - commonNetwork
    links:
      - mysqld:mysqld
    ports:
      - "8081:8081"
      - "8080:8080"
volumes:
  dbdata:
    driver: local

networks:
  commonNetwork:
    driver: bridge